-- drop all qgis and web map views if exists
DROP MATERIALIZED VIEW IF EXISTS public.web_water_valve;
DROP VIEW IF EXISTS public.water_valve;
DROP MATERIALIZED VIEW IF EXISTS public.web_water_treatment;
DROP VIEW IF EXISTS public.water_treatment;
DROP MATERIALIZED VIEW IF EXISTS public.web_water_tank;
DROP VIEW IF EXISTS public.water_tank;
DROP MATERIALIZED VIEW IF EXISTS public.web_water_reservoir;
DROP VIEW IF EXISTS public.water_reservoir;
DROP MATERIALIZED VIEW IF EXISTS public.web_water_pump;
DROP VIEW IF EXISTS public.water_pump;
DROP MATERIALIZED VIEW IF EXISTS public.web_water_pipe;
DROP VIEW IF EXISTS public.water_pipe;
DROP MATERIALIZED VIEW IF EXISTS public.web_water_part;
DROP VIEW IF EXISTS public.water_part;
DROP MATERIALIZED VIEW IF EXISTS public.web_water_motor;
DROP VIEW IF EXISTS public.water_motor;
DROP MATERIALIZED VIEW IF EXISTS public.web_water_meter;
DROP VIEW IF EXISTS public.water_meter;
DROP MATERIALIZED VIEW IF EXISTS public.web_water_manhole_trunk;
DROP VIEW IF EXISTS public.water_manhole_trunk;
DROP MATERIALIZED VIEW IF EXISTS public.web_water_manhole_cover;
DROP VIEW IF EXISTS public.water_manhole_cover;
DROP MATERIALIZED VIEW IF EXISTS public.web_water_hydrant;
DROP VIEW IF EXISTS public.water_hydrant;
DROP MATERIALIZED VIEW IF EXISTS public.web_water_control;
DROP VIEW IF EXISTS public.water_control;
DROP MATERIALIZED VIEW IF EXISTS public.web_water_box;
DROP VIEW IF EXISTS public.water_box;
DROP MATERIALIZED VIEW IF EXISTS public.web_wastewater_valve;
DROP VIEW IF EXISTS public.wastewater_valve;
DROP MATERIALIZED VIEW IF EXISTS public.web_wastewater_treatment;
DROP VIEW IF EXISTS public.wastewater_treatment;
DROP MATERIALIZED VIEW IF EXISTS public.web_wastewater_tank;
DROP VIEW IF EXISTS public.wastewater_tank;
DROP MATERIALIZED VIEW IF EXISTS public.web_wastewater_reservoir;
DROP VIEW IF EXISTS public.wastewater_reservoir;
DROP MATERIALIZED VIEW IF EXISTS public.web_wastewater_pump;
DROP VIEW IF EXISTS public.wastewater_pump;
DROP MATERIALIZED VIEW IF EXISTS public.web_wastewater_pipe;
DROP VIEW IF EXISTS public.wastewater_pipe;
DROP MATERIALIZED VIEW IF EXISTS public.web_wastewater_part;
DROP VIEW IF EXISTS public.wastewater_part;
DROP MATERIALIZED VIEW IF EXISTS public.web_wastewater_motor;
DROP VIEW IF EXISTS public.wastewater_motor;
DROP MATERIALIZED VIEW IF EXISTS public.web_wastewater_meter;
DROP VIEW IF EXISTS public.wastewater_meter;
DROP MATERIALIZED VIEW IF EXISTS public.web_wastewater_manhole_trunk;
DROP VIEW IF EXISTS public.wastewater_manhole_trunk;
DROP MATERIALIZED VIEW IF EXISTS public.web_wastewater_manhole_cover;
DROP VIEW IF EXISTS public.wastewater_manhole_cover;
DROP MATERIALIZED VIEW IF EXISTS public.web_wastewater_control;
DROP VIEW IF EXISTS public.wastewater_control;
DROP MATERIALIZED VIEW IF EXISTS public.web_wastewater_cleanout;
DROP VIEW IF EXISTS public.wastewater_cleanout;
DROP MATERIALIZED VIEW IF EXISTS public.web_wastewater_box;
DROP VIEW IF EXISTS public.wastewater_box;
DROP MATERIALIZED VIEW IF EXISTS public.web_transportation_traffic_sign_or_signal;
DROP VIEW IF EXISTS public.transportation_traffic_sign_or_signal;
DROP MATERIALIZED VIEW IF EXISTS public.web_transportation_road_overlay;
DROP VIEW IF EXISTS public.transportation_road_overlay;
DROP MATERIALIZED VIEW IF EXISTS public.web_transportation_pole;
DROP VIEW IF EXISTS public.transportation_pole;
DROP MATERIALIZED VIEW IF EXISTS public.web_transportation_pedestrian_walkway;
DROP VIEW IF EXISTS public.transportation_pedestrian_walkway;
DROP MATERIALIZED VIEW IF EXISTS public.web_transportation_light;
DROP VIEW IF EXISTS public.transportation_light;
DROP MATERIALIZED VIEW IF EXISTS public.web_transportation_base;
DROP VIEW IF EXISTS public.transportation_base;
DROP MATERIALIZED VIEW IF EXISTS public.web_transportation_barrier_or_fence;
DROP VIEW IF EXISTS public.transportation_barrier_or_fence;
DROP MATERIALIZED VIEW IF EXISTS public.web_structure_recreational;
DROP VIEW IF EXISTS public.structure_recreational;
DROP MATERIALIZED VIEW IF EXISTS public.web_structure_monument;
DROP VIEW IF EXISTS public.structure_monument;
DROP MATERIALIZED VIEW IF EXISTS public.web_structure_engineered_land;
DROP VIEW IF EXISTS public.structure_engineered_land;
DROP MATERIALIZED VIEW IF EXISTS public.web_structure_building;
DROP VIEW IF EXISTS public.structure_building;
DROP MATERIALIZED VIEW IF EXISTS public.web_structure_bridge;
DROP VIEW IF EXISTS public.structure_bridge;
DROP MATERIALIZED VIEW IF EXISTS public.web_structure_barrier_or_fence;
DROP VIEW IF EXISTS public.structure_barrier_or_fence;
DROP MATERIALIZED VIEW IF EXISTS public.web_structure_amenity;
DROP VIEW IF EXISTS public.structure_amenity;
DROP MATERIALIZED VIEW IF EXISTS public.web_stormwater_valve;
DROP VIEW IF EXISTS public.stormwater_valve;
DROP MATERIALIZED VIEW IF EXISTS public.web_stormwater_treatment;
DROP VIEW IF EXISTS public.stormwater_treatment;
DROP MATERIALIZED VIEW IF EXISTS public.web_stormwater_tank;
DROP VIEW IF EXISTS public.stormwater_tank;
DROP MATERIALIZED VIEW IF EXISTS public.web_stormwater_reservoir;
DROP VIEW IF EXISTS public.stormwater_reservoir;
DROP MATERIALIZED VIEW IF EXISTS public.web_stormwater_pump;
DROP VIEW IF EXISTS public.stormwater_pump;
DROP MATERIALIZED VIEW IF EXISTS public.web_stormwater_pipe;
DROP VIEW IF EXISTS public.stormwater_pipe;
DROP MATERIALIZED VIEW IF EXISTS public.web_stormwater_part;
DROP VIEW IF EXISTS public.stormwater_part;
DROP MATERIALIZED VIEW IF EXISTS public.web_stormwater_motor;
DROP VIEW IF EXISTS public.stormwater_motor;
DROP MATERIALIZED VIEW IF EXISTS public.web_stormwater_meter;
DROP VIEW IF EXISTS public.stormwater_meter;
DROP MATERIALIZED VIEW IF EXISTS public.web_stormwater_manhole_trunk;
DROP VIEW IF EXISTS public.stormwater_manhole_trunk;
DROP MATERIALIZED VIEW IF EXISTS public.web_stormwater_manhole_cover;
DROP VIEW IF EXISTS public.stormwater_manhole_cover;
DROP MATERIALIZED VIEW IF EXISTS public.web_stormwater_grate;
DROP VIEW IF EXISTS public.stormwater_grate;
DROP MATERIALIZED VIEW IF EXISTS public.web_stormwater_control;
DROP VIEW IF EXISTS public.stormwater_control;
DROP MATERIALIZED VIEW IF EXISTS public.web_stormwater_channel;
DROP VIEW IF EXISTS public.stormwater_channel;
DROP MATERIALIZED VIEW IF EXISTS public.web_stormwater_catch_basin;
DROP VIEW IF EXISTS public.stormwater_catch_basin;
DROP MATERIALIZED VIEW IF EXISTS public.web_stormwater_box;
DROP VIEW IF EXISTS public.stormwater_box;
DROP MATERIALIZED VIEW IF EXISTS public.web_natural_wetland;
DROP VIEW IF EXISTS public.natural_wetland;
DROP MATERIALIZED VIEW IF EXISTS public.web_natural_waterway;
DROP VIEW IF EXISTS public.natural_waterway;
DROP MATERIALIZED VIEW IF EXISTS public.web_natural_waterbody;
DROP VIEW IF EXISTS public.natural_waterbody;
DROP MATERIALIZED VIEW IF EXISTS public.web_natural_vegetation;
DROP VIEW IF EXISTS public.natural_vegetation;
DROP MATERIALIZED VIEW IF EXISTS public.web_natural_grassland;
DROP VIEW IF EXISTS public.natural_grassland;
DROP MATERIALIZED VIEW IF EXISTS public.web_natural_forest;
DROP VIEW IF EXISTS public.natural_forest;
DROP MATERIALIZED VIEW IF EXISTS public.web_natural_aquifer;
DROP VIEW IF EXISTS public.natural_aquifer;
DROP MATERIALIZED VIEW IF EXISTS public.web_natural_animalia;
DROP VIEW IF EXISTS public.natural_animalia;
DROP MATERIALIZED VIEW IF EXISTS public.web_fleet;
DROP VIEW IF EXISTS public.fleet;
DROP MATERIALIZED VIEW IF EXISTS public.web_equipment;
DROP VIEW IF EXISTS public.equipment;
DROP VIEW IF EXISTS public.region_community_system;
DROP VIEW IF EXISTS public.equipment_sub_class_list;
DROP VIEW IF EXISTS public.equipment_type_list;
DROP VIEW IF EXISTS public.risk_point;
DROP VIEW IF EXISTS public.risk_line;
DROP VIEW IF EXISTS public.risk_polygon;
DROP VIEW IF EXISTS public.risk_flt_equ;
DROP VIEW IF EXISTS public.long_term_projection;
DROP VIEW IF EXISTS public.capital_planning;

DROP MATERIALIZED VIEW IF EXISTS public.reporter_data;
DROP MATERIALIZED VIEW IF EXISTS feature_risk;
DROP MATERIALIZED VIEW IF EXISTS feature_pof;
DROP MATERIALIZED VIEW IF EXISTS feature_projection;
DROP MATERIALIZED VIEW IF EXISTS feature_calculation;
DROP MATERIALIZED VIEW IF EXISTS feature_calculation_lookup;
DROP MATERIALIZED VIEW IF EXISTS feature_quantity;
DROP MATERIALIZED VIEW IF EXISTS feature_unit;
