# Generated by Django 2.2.15 on 2021-06-18 02:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlit_helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureticket',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='List of feature ID for a ticket', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='featureticket',
            name='feature_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='feature id'),
        ),
    ]
