# Generated by Django 2.2.15 on 2021-08-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlit_helpdesk', '0003_feature_ticket_data_migrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureticket',
            name='feature_id',
        ),
        migrations.AddField(
            model_name='featureticket',
            name='community_code',
            field=models.CharField(blank=True, help_text='Community for this ticket', max_length=128, null=True, verbose_name='community code'),
        ),
    ]
