# Generated by Django 2.2.15 on 2021-08-02 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amlit_helpdesk', '0004_auto_20210802_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureticket',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Ticket', verbose_name='ticket'),
        ),
    ]
