# Generated by Django 2.2.15 on 2021-08-27 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0035_auto_20210827_0130'),
        ('amlit_helpdesk', '0005_auto_20210802_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurring_type', models.CharField(choices=[('Weekly', 'Weekly'), ('Biweekly', 'Biweekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=64)),
                ('next_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, help_text='If it is active, it will always create the new ticket. Make inactive to stop it to create ticket temporary. ')),
                ('last_ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_ticket', to='helpdesk.Ticket')),
                ('original_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='original_ticket', to='helpdesk.Ticket')),
                ('tickets', models.ManyToManyField(blank=True, null=True, to='helpdesk.Ticket')),
            ],
        ),
    ]
