# Generated by Django 2.2.15 on 2021-08-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlit_helpdesk', '0006_recurringticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringticket',
            name='recurring_type',
            field=models.CharField(max_length=512),
        ),
    ]
