# Generated by Django 2.2.15 on 2021-09-01 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amlit', '0013_auto_20210831_0351'),
        ('amlit_helpdesk', '0007_auto_20210831_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type_combination', models.IntegerField(help_text='Feature type combination will be used for getting all of assets fall for it for new ticket.', unique=True, verbose_name='Feature type combination')),
                ('recurring_type', models.CharField(max_length=512)),
                ('title', models.CharField(help_text='The title for the ticket.', max_length=512)),
                ('description', models.TextField(help_text='The description for the ticket.', verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type_combination', models.IntegerField(help_text='Feature type combination will be used for getting all of assets fall for it for new ticket.', verbose_name='Feature type combination')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlit.Organisation')),
                ('recurring_ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amlit_helpdesk.RecurringTicket')),
            ],
            options={
                'unique_together': {('feature_type_combination', 'organisation')},
            },
        ),
    ]
