# Generated by Django 2.2.15 on 2021-09-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amlit_helpdesk', '0008_schedulerorganisation_schedulertemplate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulerorganisation',
            unique_together=set(),
        ),
    ]
