# Generated by Django 2.2.15 on 2021-09-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amlit_helpdesk', '0009_auto_20210903_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulerorganisation',
            options={'ordering': ('feature_type_combination',)},
        ),
        migrations.AlterModelOptions(
            name='schedulertemplate',
            options={'ordering': ('feature_type_combination',)},
        ),
    ]
