__author__ = 'Irwan Fathurrahman <meomancer@gmail.com>'
__date__ = '24/08/21'

from rest_framework import serializers
from civitas.models.view.mc_exporter import McExporter


class McExporterDataSerializer(serializers.ModelSerializer):
    class Meta:
        model = McExporter
        fields = [
            "feature_id",
            "province_name",
            "province_code",
            "region_code",
            "community_name",
            "community_code",
            "system_id",
            "system_name",
            "length", 
            "area",
            "quantity",
            "renewal_cost_method",
            "maintenance_cost_method",
            "lifespan_method" ,
            "remaining_years_method",
            "maintenance_cost",
            "lifespan",
            "age", 
            "remaining_years", 
            "annual_reserve", 
            "pof_id", 
            "pof_name",
            "cof_id", 
            "cof_name",
            "risk_value", 
            "risk_level",
            "condition_id", 
            "condition_name",
            "class_name",
            "class_description",
            "sub_class_id", 
            "sub_class_name",
            "sub_class_description", 
            "sub_class_deterioration_id", 
            "sub_class_unit_id", 
            "sub_class_unit_name",
            "sub_class_unit_description", 
            "type_id", 
            "asset_type_name",
            "asset_type_description", 
            "feature_description", 
            "view_name", 
            "reported_length", 
            "reported_area", 
            "lookup_unit_maintenance_cost", 
            "lookup_unit_renewal_cost", 
            "input_maintenance_cost", 
            "input_renewal_cost", 
            "maintenance_cost_calc_method", 
            "renewal_cost_calc_method", 
            "reported_maintenance_cost", 
            "reported_renewal_cost", 
            "lookup_lifespan", 
            "input_lifespan", 
            "lifespan_calc_method", 
            "reported_lifespan", 
            "install_date", 
            "inspection_date", 
            "projected_sustainable_investment", 
            "display_label", 
            "brand", 
            "model", 
            "contractor", 
            "material", 
            "diameter", 
            "width", 
            "display_id", 
            "power_output", 
            "size",
            "load_rating", 
            "depth", 
            "footprint", 
            "floor_area", 
            "height", 
            "structure_id", 
            "service", 
            "capacity", 
            "stakeholder",
            "species", 
            "gauge", 
            "phase", 
            "specification", 
            "cores", 
            "primary_voltage", 
            "secondary_voltage", 
            "voltage", 
            "current", 
            "communication", 
            "account"
        ]
