# Generated by Django 2.2.15 on 2021-04-05 06:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amlit', '0002_auto_20210318_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('code', models.CharField(max_length=8, verbose_name='Code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('max_user', models.IntegerField(verbose_name='Max user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('time_plan', models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually')], default='annually', max_length=64)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlit.Currency', verbose_name='Currency')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlit.Plan', verbose_name='Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='active', max_length=64)),
                ('date_subscribed', models.DateField(default=datetime.date.today, verbose_name='Date subscribed')),
                ('date_expired', models.DateField(blank=True, null=True, verbose_name='Date expired')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_organisation', to='amlit.Organisation', verbose_name='Organisation')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlit.SubscriptionPlan', verbose_name='Subscription plan')),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation_subscription', to='amlit.Subscription', verbose_name='Subscription'),
        ),
    ]
