# Generated by Django 2.2.15 on 2021-04-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('amlit', '0004_auto_20210416_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='subscription',
            field=models.IntegerField(default=0),
        ),
    ]
