# Generated by Django 2.2.15 on 2021-07-16 03:37

import amlit.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlit', '0006_amlitproduct'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organisation',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', amlit.models.user.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
