# Generated by Django 2.2.15 on 2021-07-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlit', '0007_auto_20210716_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='community_code',
            field=models.CharField(default='', help_text='Community for this organisation', max_length=128, unique=True, verbose_name='community code '),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='amlit.RolePermission', verbose_name='permissions'),
        ),
    ]
