# Generated by Django 2.2.15 on 2021-07-22 07:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('amlit', '0008_auto_20210716_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrganisationInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text=('Unique id for the invitation',), unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlit.Organisation', verbose_name='organisation')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amlit.UserRole', verbose_name='role')),
            ],
            options={
                'unique_together': {('email', 'organisation')},
            },
        ),
    ]
