# Generated by Django 2.2.15 on 2021-07-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlit', '0009_userorganisationinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar'),
        ),
    ]
