# Generated by Django 2.2.15 on 2021-08-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0034_create_email_template_for_merged'),
        ('amlit', '0011_sitepreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreferences',
            name='recurred_queues',
            field=models.ManyToManyField(blank=True, help_text='The Queue list that can be create the recurring tickets.', null=True, to='helpdesk.Queue'),
        ),
    ]
