# Generated by Django 2.2.15 on 2021-08-31 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amlit', '0012_sitepreferences_recurred_queues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='usertitle',
            options={'ordering': ('name',)},
        ),
    ]
