# Generated by Django 2.2.15 on 2021-09-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amlit', '0013_auto_20210831_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='amlitproduct',
            name='best_value',
            field=models.BooleanField(default=False),
        ),
    ]
