# Generated by Django 2.2.15 on 2023-05-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amlit', '0015_organisation_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmlitProduct',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='subscription',
        ),
    ]
